// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv28e-tiI_9fW9ccUNCJeRnVHYc_CWeJ0',
    appId: '1:190652677767:web:d6ae49ea96450901e44222',
    messagingSenderId: '190652677767',
    projectId: 'warsha-counter',
    authDomain: 'warsha-counter.firebaseapp.com',
    storageBucket: 'warsha-counter.firebasestorage.app',
    measurementId: 'G-N7F33WNBMB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs25oxCI5l8reXWlp8VGNEvSNpbzTdNdg',
    appId: '1:190652677767:android:48ee4b5ff4588595e44222',
    messagingSenderId: '190652677767',
    projectId: 'warsha-counter',
    storageBucket: 'warsha-counter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGgrbYBglLaKBPDF3LQeXjXLBNtJcQgm8',
    appId: '1:190652677767:ios:16c343954c3d69e5e44222',
    messagingSenderId: '190652677767',
    projectId: 'warsha-counter',
    storageBucket: 'warsha-counter.firebasestorage.app',
    iosBundleId: 'com.example.warshaCounter',
  );
}
